import { z } from 'zod';

import { paginationSearchSchema } from '@/core/types/search-params';

export const deviceSchema = z.object({
  // Server autogenerated
  id: z.number(),
  createdAt: z.coerce.date(),
  // User generated
  name: z.string().nullable(),
  brand: z.string().nullable(),
  chip: z.string().nullable(),
  os: z.string().nullable(),
  ports: z.string().nullable(),
  available: z.boolean().default(true),
});
export const deviceFormSchema = deviceSchema.omit({
  id: true,
  createdAt: true,
});

export const devicesFiltersSchema = z.object({
  search: z.string().optional().catch('')
});
export const devicesSearchSchema = paginationSearchSchema.extend(
  devicesFiltersSchema.shape,
);
