/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppAboutRouteImport } from './routes/app/about'
import { Route as AppTransactionsRouteRouteImport } from './routes/app/transactions/route'
import { Route as AppEmployeesRouteRouteImport } from './routes/app/employees/route'
import { Route as AppDummiesRouteRouteImport } from './routes/app/dummies/route'
import { Route as AppDrivesRouteRouteImport } from './routes/app/drives/route'
import { Route as AppDevicesRouteRouteImport } from './routes/app/devices/route'
import { Route as AppTransactionsIndexRouteImport } from './routes/app/transactions/index'
import { Route as AppEmployeesIndexRouteImport } from './routes/app/employees/index'
import { Route as AppDummiesIndexRouteImport } from './routes/app/dummies/index'
import { Route as AppDrivesIndexRouteImport } from './routes/app/drives/index'
import { Route as AppDevicesIndexRouteImport } from './routes/app/devices/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTransactionsRouteRoute = AppTransactionsRouteRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEmployeesRouteRoute = AppEmployeesRouteRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDummiesRouteRoute = AppDummiesRouteRouteImport.update({
  id: '/dummies',
  path: '/dummies',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDrivesRouteRoute = AppDrivesRouteRouteImport.update({
  id: '/drives',
  path: '/drives',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDevicesRouteRoute = AppDevicesRouteRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTransactionsIndexRoute = AppTransactionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTransactionsRouteRoute,
} as any)
const AppEmployeesIndexRoute = AppEmployeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEmployeesRouteRoute,
} as any)
const AppDummiesIndexRoute = AppDummiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDummiesRouteRoute,
} as any)
const AppDrivesIndexRoute = AppDrivesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDrivesRouteRoute,
} as any)
const AppDevicesIndexRoute = AppDevicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDevicesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/devices': typeof AppDevicesRouteRouteWithChildren
  '/app/drives': typeof AppDrivesRouteRouteWithChildren
  '/app/dummies': typeof AppDummiesRouteRouteWithChildren
  '/app/employees': typeof AppEmployeesRouteRouteWithChildren
  '/app/transactions': typeof AppTransactionsRouteRouteWithChildren
  '/app/about': typeof AppAboutRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/devices/': typeof AppDevicesIndexRoute
  '/app/drives/': typeof AppDrivesIndexRoute
  '/app/dummies/': typeof AppDummiesIndexRoute
  '/app/employees/': typeof AppEmployeesIndexRoute
  '/app/transactions/': typeof AppTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/about': typeof AppAboutRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/devices': typeof AppDevicesIndexRoute
  '/app/drives': typeof AppDrivesIndexRoute
  '/app/dummies': typeof AppDummiesIndexRoute
  '/app/employees': typeof AppEmployeesIndexRoute
  '/app/transactions': typeof AppTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/devices': typeof AppDevicesRouteRouteWithChildren
  '/app/drives': typeof AppDrivesRouteRouteWithChildren
  '/app/dummies': typeof AppDummiesRouteRouteWithChildren
  '/app/employees': typeof AppEmployeesRouteRouteWithChildren
  '/app/transactions': typeof AppTransactionsRouteRouteWithChildren
  '/app/about': typeof AppAboutRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/devices/': typeof AppDevicesIndexRoute
  '/app/drives/': typeof AppDrivesIndexRoute
  '/app/dummies/': typeof AppDummiesIndexRoute
  '/app/employees/': typeof AppEmployeesIndexRoute
  '/app/transactions/': typeof AppTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/devices'
    | '/app/drives'
    | '/app/dummies'
    | '/app/employees'
    | '/app/transactions'
    | '/app/about'
    | '/app/dashboard'
    | '/app/settings'
    | '/app/'
    | '/app/devices/'
    | '/app/drives/'
    | '/app/dummies/'
    | '/app/employees/'
    | '/app/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/about'
    | '/app/dashboard'
    | '/app/settings'
    | '/app'
    | '/app/devices'
    | '/app/drives'
    | '/app/dummies'
    | '/app/employees'
    | '/app/transactions'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/devices'
    | '/app/drives'
    | '/app/dummies'
    | '/app/employees'
    | '/app/transactions'
    | '/app/about'
    | '/app/dashboard'
    | '/app/settings'
    | '/app/'
    | '/app/devices/'
    | '/app/drives/'
    | '/app/dummies/'
    | '/app/employees/'
    | '/app/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/about': {
      id: '/app/about'
      path: '/about'
      fullPath: '/app/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/employees': {
      id: '/app/employees'
      path: '/employees'
      fullPath: '/app/employees'
      preLoaderRoute: typeof AppEmployeesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dummies': {
      id: '/app/dummies'
      path: '/dummies'
      fullPath: '/app/dummies'
      preLoaderRoute: typeof AppDummiesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/drives': {
      id: '/app/drives'
      path: '/drives'
      fullPath: '/app/drives'
      preLoaderRoute: typeof AppDrivesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/devices': {
      id: '/app/devices'
      path: '/devices'
      fullPath: '/app/devices'
      preLoaderRoute: typeof AppDevicesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/transactions/': {
      id: '/app/transactions/'
      path: '/'
      fullPath: '/app/transactions/'
      preLoaderRoute: typeof AppTransactionsIndexRouteImport
      parentRoute: typeof AppTransactionsRouteRoute
    }
    '/app/employees/': {
      id: '/app/employees/'
      path: '/'
      fullPath: '/app/employees/'
      preLoaderRoute: typeof AppEmployeesIndexRouteImport
      parentRoute: typeof AppEmployeesRouteRoute
    }
    '/app/dummies/': {
      id: '/app/dummies/'
      path: '/'
      fullPath: '/app/dummies/'
      preLoaderRoute: typeof AppDummiesIndexRouteImport
      parentRoute: typeof AppDummiesRouteRoute
    }
    '/app/drives/': {
      id: '/app/drives/'
      path: '/'
      fullPath: '/app/drives/'
      preLoaderRoute: typeof AppDrivesIndexRouteImport
      parentRoute: typeof AppDrivesRouteRoute
    }
    '/app/devices/': {
      id: '/app/devices/'
      path: '/'
      fullPath: '/app/devices/'
      preLoaderRoute: typeof AppDevicesIndexRouteImport
      parentRoute: typeof AppDevicesRouteRoute
    }
  }
}

interface AppDevicesRouteRouteChildren {
  AppDevicesIndexRoute: typeof AppDevicesIndexRoute
}

const AppDevicesRouteRouteChildren: AppDevicesRouteRouteChildren = {
  AppDevicesIndexRoute: AppDevicesIndexRoute,
}

const AppDevicesRouteRouteWithChildren = AppDevicesRouteRoute._addFileChildren(
  AppDevicesRouteRouteChildren,
)

interface AppDrivesRouteRouteChildren {
  AppDrivesIndexRoute: typeof AppDrivesIndexRoute
}

const AppDrivesRouteRouteChildren: AppDrivesRouteRouteChildren = {
  AppDrivesIndexRoute: AppDrivesIndexRoute,
}

const AppDrivesRouteRouteWithChildren = AppDrivesRouteRoute._addFileChildren(
  AppDrivesRouteRouteChildren,
)

interface AppDummiesRouteRouteChildren {
  AppDummiesIndexRoute: typeof AppDummiesIndexRoute
}

const AppDummiesRouteRouteChildren: AppDummiesRouteRouteChildren = {
  AppDummiesIndexRoute: AppDummiesIndexRoute,
}

const AppDummiesRouteRouteWithChildren = AppDummiesRouteRoute._addFileChildren(
  AppDummiesRouteRouteChildren,
)

interface AppEmployeesRouteRouteChildren {
  AppEmployeesIndexRoute: typeof AppEmployeesIndexRoute
}

const AppEmployeesRouteRouteChildren: AppEmployeesRouteRouteChildren = {
  AppEmployeesIndexRoute: AppEmployeesIndexRoute,
}

const AppEmployeesRouteRouteWithChildren =
  AppEmployeesRouteRoute._addFileChildren(AppEmployeesRouteRouteChildren)

interface AppTransactionsRouteRouteChildren {
  AppTransactionsIndexRoute: typeof AppTransactionsIndexRoute
}

const AppTransactionsRouteRouteChildren: AppTransactionsRouteRouteChildren = {
  AppTransactionsIndexRoute: AppTransactionsIndexRoute,
}

const AppTransactionsRouteRouteWithChildren =
  AppTransactionsRouteRoute._addFileChildren(AppTransactionsRouteRouteChildren)

interface AppRouteRouteChildren {
  AppDevicesRouteRoute: typeof AppDevicesRouteRouteWithChildren
  AppDrivesRouteRoute: typeof AppDrivesRouteRouteWithChildren
  AppDummiesRouteRoute: typeof AppDummiesRouteRouteWithChildren
  AppEmployeesRouteRoute: typeof AppEmployeesRouteRouteWithChildren
  AppTransactionsRouteRoute: typeof AppTransactionsRouteRouteWithChildren
  AppAboutRoute: typeof AppAboutRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDevicesRouteRoute: AppDevicesRouteRouteWithChildren,
  AppDrivesRouteRoute: AppDrivesRouteRouteWithChildren,
  AppDummiesRouteRoute: AppDummiesRouteRouteWithChildren,
  AppEmployeesRouteRoute: AppEmployeesRouteRouteWithChildren,
  AppTransactionsRouteRoute: AppTransactionsRouteRouteWithChildren,
  AppAboutRoute: AppAboutRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
